# Generated by Django 4.2.17 on 2024-12-16 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('publication_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000, 'Publication year must be after 1000'), django.core.validators.MaxValueValidator(2024, 'Publication year cannot be in the future')])),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('total_pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Books must have at least 1 page')])),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0, 'Minimum rating is 1'), django.core.validators.MaxValueValidator(5.0, 'Maximum rating is 5')])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
